### ISSUE TITLE
error 404 - redirects to non existing page on install

### ISSUE THREAD

**Issue by alsguimaraes** [Shopify/shopify-demo-app-node-react#12]
Upon installation of the app, the new page (Select Products) shows briefly, and then redirects to the infamous "the page you're looking for couldn't be found" page.

Is this a known issue? Is there a workaround?

p.s.: I am running on heroku.  It required minor changes on the build scripts.

**Comment by tylerball** [comment]
It looks like you might not have the app set up correctly based on the issue you just opened. You should not be accessing the app via `localhost:3000`, but via a tunnel, like ngrok. Have a look at [this page](https://developers.shopify.com/tutorials/build-a-shopify-app-with-node-and-react/embed-your-app-in-shopify) for instructions to how to run a tunnel and configure the URL in the Partners Dashboard so that it redirects to your store properly.

**Comment by alsguimaraes** [comment]
I believe I have finally figured it out. 
It turns out that the npm script on package.json "next start" does not work as expected.
A workaround is to run "node server.js" locally, or "node server.js -p $PORT" on heroku.
I hope this helps other people with the same issue.

**Comment by alsguimaraes** [comment]
I am running on Chrome 74.
The dev shop is https://xp-dev.myshopify.com/. 

Thanks.

**Comment by alsguimaraes** [comment]
In summary, "next start" does not seem to work. I am not sure why.
Using "node server.js" locally, or "node server.js -p $PORT" on heroku does the trick.
Thanks, for your help. Closing the issue.

**Comment by tylerball** [comment]
Hi @alsguimaraes, which browser are you using? Also if you could provide me with a shop the app is installed on I could try to debug it for you.
