### ISSUE TITLE
Can't authenticate app

### ISSUE THREAD

**Issue by paulkre** [Shopify/shopify-demo-app-node-react#20]
# Bug summary

I get the following error when I try to authenticate my app via OAuth:

`Oauth error invalid_request: The Shopify API application does not support oauth`

## Expected behavior

Shopify OAuth dialog for the private app appears in the browser.

## Actual behavior

After redirecting, Shopify shows the following page:

![Screenshot 2019-05-23 at 12 39 10](https://user-images.githubusercontent.com/13008492/58246681-feaeb500-7d57-11e9-8186-5bfd5fcbb730.png)

## Steps to reproduce the problem

1. Create private app in Shopify admin area
1. Clone the repository
1. Copy `SHOPIFY_API_KEY` and `SHOPIFY_API_SECRET_KEY` from private app settings to .env file in repository
1. `npm install`
1. `npm run dev`
1. `ngrok http 3000`
1. Go to `https://[NGROK_ID].ngrok.io/auth?shop=[SHOP_SLUG].myshopify.com`

## Specifications

- Browser: Chrome
- Device: MacBook Pro Early 2015
- Operating System: macOS Mojave 10.14.4

**Comment by nwtn** [comment]
Hi @paulkre. Do you have your ngrok URLs set as your app URL and whitelisted redirection URL in the partner dashboard? (See https://developers.shopify.com/tutorials/build-a-shopify-app-with-node-and-react/embed-your-app-in-shopify#get-a-shopify-api-key for more)

**Comment by paulkre** [comment]
Hi @nwtn, thanks for the reply. In fact I have not whitelisted the URL yet.
When I create a new private app I can not find any input fields labeled "App URL" or "Whitelisted redirection URL(s)" as shown in the tutorial.
Where do you specify whitelisted URLs for a private app?

**Comment by nwtn** [comment]
Ah, my mistake. I didn’t notice that you said you were building a private app. Private apps use a different kind of auth than public apps.

I’d say your best bet to get help on private app auth would be to check out our [docs on Private app authorization](https://help.shopify.com/en/api/getting-started/authentication/private-authentication) or post to our [API & SDK Community forum](https://community.shopify.com/c/Shopify-APIs-SDKs/bd-p/shopify-apis-and-technology).

Since this tutorial is focused on building public apps, I’m going to close this issue as out-of-scope for this repo. Good luck!
