### ISSUE TITLE
HMAC validation failed

### ISSUE THREAD

**Issue by sunnyrvtech** [Shopify/shopify-demo-app-node-react#23]
I got this issue "HMAC validation failed". When i removed this server.use(verifyRequest()); It is working fine but i need this verfyRequest . So please help me to solve this issue.Thanks

**Comment by tiffanytse** [comment]
Could you provide a bit more context as to your setup; and a more detailed log of the error message too. Thanks!

**Comment by katiedavis** [comment]
@sunnyrvtech Just wanted to follow up and see if you're still having this issue and if you wanted to provide more details? 
I also wanted to make sure you take a look at the `shopify-koa-auth` docs:
https://github.com/Shopify/quilt/tree/master/packages/koa-shopify-auth

**Comment by sunny047** [comment]
Hi @katiedavis 

Yes i am still getting this issue . I have checked the same code in my linux system and here it is working fine . The issue i am getting in the window7 pc.

**Comment by sunny047** [comment]
Also getting one more issue after click on choose product from resource picker component. 

"Network error: Unexpected token U in JSON at position 0"

graphql query return 403 response.  I think the header is not sent with request thats why it return 403 response.

In this package ,there are lots of issue . I have already mentioned about build production issue . But this issue is removed from the list .Not sure why ?

Is there any demo that works well without any issues ?

**Comment by ranjitatwal30** [comment]
facing same issue while deploying my app on heroku, any update on this one ?

**Comment by katiedavis** [comment]
For more information on deploying your app to heroku, please consider using the [Shopify-App-CLI](https://github.com/Shopify/shopify-app-cli/)

There's detailed information on deploying [here](https://github.com/Shopify/shopify-app-cli/issues/277)
