### ISSUE TITLE
Receiving 404 errors on auth installation page in production mode 

### ISSUE THREAD

**Issue by Popesites** [Shopify/shopify-demo-app-node-react#27]
# Bug summary

I'm currently receiving issues when running the app in production mode. When I navigate to https://APP_NAME.com/auth?shop=<my_shop_address> it results in a 404 page:

<img width="1437" alt="Screen Shot 2019-06-11 at 7 37 26 PM" src="https://user-images.githubusercontent.com/17707366/59319676-6afa4580-8c80-11e9-99cb-9dac4d46cac9.png">

I can confirm that in development mode, it functions properly. 

## Expected behavior

It should redirect the user to the installation page. 

## Steps to reproduce the problem

1. Download Starter Files
2. Run npm run build
3. Run npm start

**Comment by tiffanytse** [comment]
Thanks for flagging; we'll look into it shortly!

**Comment by sunnyrvtech** [comment]
Any update ?  I got the same issue.

**Comment by tim-phillips** [comment]
@sunnyrvtech See #28

**Comment by sunnyrvtech** [comment]
Okay what about the production build issue as mentioned by @Popesites

**Comment by tim-phillips** [comment]
I have nothing to report on that issue.

**Comment by katiedavis** [comment]
Hi @Popesites. The guide doesn't cover deploying at the moment, but I have a feeling that the issue you're having is because `npm run build` builds the front end of the app.
Because this has a custom server, you'll need to modify the build command.
I found this on the next forums:
https://spectrum.chat/next-js/general/custom-server-in-production~81cd6879-9d7f-41b8-be3f-f69d86214d33
You'll probably want to write a small script that includes `'NODE_ENV=production node server.js`

I'm going to add a feature-request tag to this as we've had a couple people asking about building for production :)
