### ISSUE TITLE
After Installation from app store, it shows page not found

### ISSUE THREAD

**Issue by ranjitatwal30** [Shopify/shopify-demo-app-node-react#51]
# Bug summary

While development and testing to install app on the test stores, never faced this issue, but while installing app from play store for the first time, it shows "The page you’re looking for couldn’t be found".

Now there's a catch. When I try to install app again it works ok. Something to do with enable cookies ?

Tip: try installing app in private browser mode, as I guess it's related to cookies.

**Comment by katiedavis** [comment]
Hey @ranjitatwal30 there's actually a fix in place for this bug right now [here](https://github.com/Shopify/quilt/pull/1022) in the auth package. I'll be reviewing and it will be merged soon.

**Comment by ranjitatwal30** [comment]
thanks @katiedavis , for the quick update. Awaiting for the merge...

**Comment by katiedavis** [comment]
Hey @ranjitatwal30 it should be live within the next hour.

**Comment by katiedavis** [comment]
I forgot to mention you'll need to npm update

**Comment by ranjitatwal30** [comment]
> I forgot to mention you'll need to npm update

sure, will do !

**Comment by junaid33** [comment]
I'm still getting this issue. I have updated the package to the latest, but when I submitted my app for approval, this error is causing them to reject the application. I'm using a prefix for the auth route (shopify/auth instead of just /auth). Could this be related to: 
https://github.com/Shopify/quilt/issues/1148
