### ISSUE TITLE
Login/Install page route example

### ISSUE THREAD

**Issue by patryk-smc** [Shopify/shopify-demo-app-node-react#6]
# Issue summary

Could you provide an example of login/install page route such as https://import-store.shopifyapps.com/?

**Comment by gfscott** [comment]
Hi @patryk-smc, thanks for filing an issue! We’ll investigate this as an enhancement for a future update to the tutorial.

**Comment by nwtn** [comment]
@patryk-smc Thanks for the suggestion, we’ll look at this for our roadmap for future iterations of the tutorial. We descoped this from the initial iteration of the tutorial because this functionality and UX is not something that’s necessary for public apps (i.e. apps published in the App Store).

In the meantime, you may have some luck getting suggestions from our support team and other partners by posting about this in our [APIs & SDKs Community forum](https://community.shopify.com/c/Shopify-APIs-SDKs/bd-p/shopify-apis-and-technology).
